### ISSUE TITLE
Parallelization of Code Signing

### ISSUE THREAD

**Issue by milend** [isignpy/isign#33]
Code signing of large applications can be prohibitive for incremental builds (e.g., 10-30s on each build just to perform code signing).

The process seems trivially parallelizable:
- `CodeResources`: the [computation](https://github.com/isignpy/isign/blob/master/isign/code_resources.py#L144-L145) of the SHA1 and SHA256 hashes of all resource files can be done in parallel.
- Mach-O files: According to @michaeleisel, code signing for executables is done on a per-page basis, so there might be potential for parallelization there.

**Comment by neilk** [comment]
Hi, Milend. It definitely could be made faster that way. However, in my experience, the majority of time is spent decompressing and then re-compressing the app.

I wrote some docs on this [a long time ago](https://github.com/isignpy/isign/blob/master/docs/speed.md). Some of it is out of date, but it's mostly still true.

However, if you are looking for every last cycle of speed, I can help you. Please feel free to contact me at neilk@neilk.net. I completed a contract with a large company recently (I believe you know them) and while COVID has somewhat delayed my plans for this library, I want to find new sponsors for ongoing development.

**Comment by milend** [comment]
> However, in my experience, the majority of time is spent decompressing and then re-compressing the app. So it's hard to justify the work when you don't get even a 50% speedup.

That would depend on the use case/apps in question. For some specific uses cases of mine, I wrote a prototype that suggested that parallelisation can end up reducing the signing time somewhere between 50-75%, so definitely worth it.

> I wrote some docs on this a long time ago. Some of it is out of date, but it's mostly still true. Perhaps there are more radical approaches still to be taken that I haven't thought of.

I'm focused on the incremental build use case, so there's no compression happening at all (i.e., we just sign after building the binary, there's no IPA creation).

I'll close the issue as I just wanted to bring the potential wins to your attention 🙂

**Comment by neilk** [comment]
Ah yes, if you are going from .app directory to .app directory there are some much bigger wins to be had!

I'm trying to put a roadmap together and if this is important for you then I think we can add it
