### ISSUE TITLE
Verify isign's feature set with XCode 11 / iOS 12

### ISSUE THREAD

**Issue by neilk** [isignpy/isign#8]
Ensure that isign can re-sign apps for this platform, without removing any functionality from the app, and install the app on an iOS 12 device. Installation can be manual; this does not include the Apple iOS app store.

May require rooting around in forked versions of isign, or unmerged PRs, for various issues not fixed in the main repo. In particular, should ensure that WatchKit "appex" extensions are not stripped from the resigned app.

**Comment by sah** [comment]
Gonna mark this "done", since it has been investigated. It doesn't work, and I think it's best to track fixes in separate issues since it's unclear how many will be needed.
